name: CI
on: 
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: [windows-latest]  
    if: "!contains(github.event.head_commit.message, '[skip ci]') && github.event.head_commit.message != 'Auto-Build'"
  
    steps:
    - uses: actions/checkout@v2-beta
      with:
        token: ${{ secrets.PAT }}
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    
    - run: npm install
    - run: npm run build

    - run: git config --global user.name "Sam Marsh"
    - run: git config --global user.email "ISmarsh@users.noreply.github.com"
    - run: git add -A
    - run: git commit -m "Auto-Build"
    - run: git push    
