name: CI
on: [push]
jobs:
  build:
    runs-on: [ubuntu-latest]  

    steps:
    - uses: actions/checkout@v2-beta
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    
    - run: npm install
    - run: npm run build

    - name: commit    
      run: |
        git config --global user.name "Sam Marsh"
        git config --global user.email "ISmarsh@users.noreply.github.com"
        git commit -am "auto-build"
        git push
