name: CI
on: [push]
jobs:
  build:
    runs-on: [windows-latest]  

    steps:
    - uses: actions/checkout@v2-beta
      with:
        token: ${{ secrets.PAT }}
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    
    - run: npm install
    - run: npm run build

    - run: git config --global user.name "Sam Marsh"
    - run: git config --global user.email "ISmarsh@users.noreply.github.com"
    - run: git add -A
    - run: git commit -m "Auto-Build"
    - run: git push    
